### ISSUE TITLE
Awesome! :)

### ISSUE THREAD

**Issue by xorander00** [cneira/jail-task-driver#1]
I happened to run across this repo while searching github & saw that it was very recently published.  I was contemplating building something like this for myself, but yours is obviously much further along.  I don't know the details for implementing Nomad task drivers, but I'll read the documentation & review your codebase to get the idea so that hopefully I can contribute some code.
  
I'm going to test this out this week and see how it works for my uses.  I saw the TODO list and have a couple of questions/comments:  
  
- How are you thinking about implementing docker support?  The only ways I can think of doing it are by either implementing docker & augmented Linuxulator for it (big undertaking), updating the community port (very outdated), or using a bhyve VM inside the jail and using the up-to-date ported docker client to control it from the jail.  Another option could be to grab the docker image tarball, extract it, & patch it up to run within the jail, but this is not an area I'm super familiar with yet.  I'm wondering how automated the transformation could be for converting a docker image to OCI. 
  
- Would exploring CloudABI be of any use here?  It's supposed to be able to run containers as part of a Kubernetes cluster via Scuba.
  
- I'd love to be able to ZFS send/recv datasets, much like artifacts in Nomad jobs are for downloading files, before starting jails.  This is something that I might actually be willing to implement and submit a PR for, if possible.  Any advice?  
  
Thanks & looking forward to further development on this! :)

**Comment by cneira** [comment]
@xorander00 
Thank you very much for checking this out!. 

* About docker support my main idea was to grab the docker image tarball, extract it and use that dataset to run the jail, In the past at least compiling the Linux kernel worked inside a jail.

* I have read of CloudABI and Scuba but have not used them.

* That would be great the only downside that jail creation will take longer if we are downloading zfs datasets when the job start.


Bests

**Comment by xorander00** [comment]
@cneira 

- Sounds like a plan!  
  
- I'm not sure that it would have a direct impact on this, but I know the aims somewhat overlap, so it could be useful for future consideration.  
  
- Totally agree.  I tend to lean towards leaving it up to the administrator and just warning them that network transfer times must be considered on this front.  The good side is that incremental snapshots + send/recv mitigate that, in which case only the first transfer takes a while (or the server could pre-provision it before the job is even allocated) after which incremental snapshots should be smaller.  The other alternative I'm considering is using iSCSI to mount dedicated zpools, but that would be a pain (although having an iSCSI target as an option could also be worth it).  The main point for me is that the main jail datasets are stored on a remote server, so they would need to be accessed remotely (i.e. iSCSI, NFS, etc) or transferred first & accessed locally (i.e. zfs send/recv via dataset or tarball).  I was also considering just using artifact { ... } in the job spec and downloading a tarball.gz of the dataset, and then restoring via zfs in the job command before launching the jail.

**Comment by cneira** [comment]
@xorander00  I'm closing this feel to reopen when work on this is started.
